project/app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /app/5/
    path("<int:categorie_id>/", views.detail, name="detail"),
    # ex: /app/5/results/
    path("<int:cible_id>/results/", views.results, name="results"),
    # ex: /app/5/vote/
    path("<int:cible_id>/vote/", views.vote, name="vote"),
    path("", views.get_list, name="get_list"),
    path("cible/add/", views.add_cible_view, name='cible_add'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("app/", include("app.urls")),
    path("admin/", admin.site.urls),
]

project/app/models.py
from django.db import models

class Categorie(models.Model):
    nom_categorie = models.CharField(max_length=200)
    def __str__(self):
        return self.nom_categorie


class Cible(models.Model):
    classement = models.IntegerField(unique=True)
    nom = models.CharField(max_length=200)
    prenom = models.CharField(max_length=200)
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.classement) + ") " + self.nom.upper() + " " + self.prenom.title() + " : " + str(self.categorie)

project/app/forms.py
from django import forms
from .models import Cible

class CibleForm(forms.ModelForm):
    class Meta:
        model = Cible
        fields = ['nom', 'prenom', 'categorie']

project/app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.template import loader
from .forms import CibleForm
from .models import Cible, Categorie


def index(request):
    worst_targets = Cible.objects.order_by("classement")[:5]
    context = {"worst_targets" : worst_targets}
    return render(request, "app/index.html", context)

# Leave the rest of the views (detail, results, vote) unchanged

def detail(request, categorie_id):
    categorie = get_object_or_404(Categorie, id=categorie_id)
    return render(request, "app/detail.html", {"categorie": categorie})


def results(request, cible_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % cible_id)


def vote(request, cible_id):
    return HttpResponse("You're voting on question %s." % cible_id)

def get_list(request):
    targets = Cible.objects.all()
    context = {"targets" : targets}
    return render(request, "app/body.html", context)


def add_cible_view(request):

    if request.method == 'POST':
        form = CibleForm(request.POST)
        if form.is_valid():
            # Calculate the new classement
            total_cibles = Cible.objects.count()
            new_classement = total_cibles + 1

            # Create and save the new cible
            cible = form.save(commit=False)
            cible.classement = new_classement
            cible.save()
            return redirect('get_list')  # Redirige vers la page principale après l'ajout
    else:
        form = CibleForm()

    return render(request, 'app/add_cible.html', {'form': form})

project/app/templates/app/add_cible.html
{% include 'app/header.html' %}


<div class="container">
    <h2>Ajouter une Cible</h2>
    <form method="post" class="my-custom-form">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_nom">Nom:</label>
            {{ form.nom }}
        </div>

        <div class="form-group">
            <label for="id_prenom">Prénom:</label>
            {{ form.prenom }}
        </div>

        <div class="form-group">
            <label for="id_categorie">Catégorie:</label>
            {{ form.categorie }}
        </div>

        <button type="submit" class="btn btn-primary">Ajouter</button>
    </form>
</div>
{% include 'app/footer.html' %}

project/app/templates/app/body.html
{% include 'app/header.html' %}

<div class="container">
    <div class="target-list">
        {% for target in targets %}
            <!-- Ajoutez une classe "target-container" pour chaque ligne -->
            <div class="target-row target-container" onmouseover="showButton(this)" onmouseout="hideButton(this)">
                <span class="column">{{target.classement}}</span>
                <span class="column">{{target.nom.upper}}</span>
                <span class="column">{{target.prenom}}</span>
                <span class="column">{{target.categorie}}</span>
                <!-- Ajoutez une div pour le contenu en déroulement -->
                <div class="hidden-content">
                    <!-- Votre contenu en déroulement ici -->
                    <button class="edit-button" onclick="editTarget({{ target.id }})">Modifier</button>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="add-cible">
        <a href="{% url 'cible_add' %}"><button id="show-form-btn">Ajouter une Cible</button></a>
    </div>
</div>

{% include 'app/footer.html' %}

project/app/templates/app/footer.html
        <footer>
            Abou El Naqi's enemies
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js "></script>
    </body>
</html>

project/app/templates/app/header.html
<html>
<head>
    {% load static %}
    <title>Black List</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css"  href="{% static 'app/css/file.css' %}">
    <script src="{% static 'app/js/file.js' %}"></script>
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <a class="nav-item nav-link active" href="{% url 'get_list' %}">List <span class="sr-only">(current)</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'cible_add' %}">add target</a>
                <a class="nav-item nav-link" href="#">Pricing</a>
                <a class="nav-item nav-link disabled" href="#">Disabled</a>
            </div>
        </div>
    </div>

project/app/templates/app/index.html
{% if worst_targets %}
    <ol>
    {% for target in worst_targets %}
        <li><a href="/app/{{ target.id }}/">{{ target }}</a></li>
    {% endfor %}
    </ol>
{% else %}
    <p>No polls are available.</p>
{% endif %}

project/app/templates/app/liste_cibles.html
<!DOCTYPE html>
<html>
<head>
    <title>Liste des Cibles</title>
</head>
<body>
    <h1>Liste des Cibles</h1>
    <ul>
        {% for cible in cibles %}
            <li>{{ cible }}</li>
        {% endfor %}
    </ul>
</body>
</html>